### ISSUE TITLE
Parse front matter

### ISSUE THREAD

**Issue by lffg** [learning-in-public/internal-links-analyzer#2]
The title of each page (which will be included in Markdown file front-matter) should also be emitted from this library since it's needed to build the Graph.

**Comment by EternalQuasar0206** [comment]
What is the title? The content inside H1? The file name?

**Comment by lffg** [comment]
> What is the title? The content inside H1? The file name?

Maybe a `title` field in the front-matter?

**Comment by EternalQuasar0206** [comment]
There is something like that? I missed it lol
